FROM node:18-alpine
WORKDIR /usr/src/app
COPY backend/package*.json ./
RUN npm install
COPY ./backend .
RUN npm test && echo "Tests passed successfully!" || echo "Tests failed. Aborting build." && npm run build
EXPOSE 3000
CMD [ "node", "dist/index.js" ]